-- Explore all objects in the Database

SELECT * from INFORMATION_SCHEMA.TABLES

-- Explore all columns in the Database

SELECT * from INFORMATION_SCHEMA.COLUMNS

-- Explore all countries are customer come from

SELECT distinct(country) from gold.dim_customers

-- Explore all categories 'The Major Divisions'

SELECT DISTINCT category, sub_category, product_name from gold.dim_products
ORDER BY 1,2,3

-- Find the date of First and Last order
-- How many years of sales are available

SELECT 
MIN(order_date) first_order_date, 
MAX(order_date) last_order_date, 
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS years_of_data
from gold.fact_sales

-- Find the youngest and oldest customer

SELECT
MIN(birth_date) oldest_birth_date,
DATEDIFF(year, MIN(birth_date), GETDATE()) AS oldest_customer_age,
MAX(birth_date) youngest_birth_date,
DATEDIFF(year, MAX(birth_date), GETDATE()) AS youngest_customer_age
FROM gold.dim_customers

-- Find the total sales

SELECT sum(sales_amount) AS total_sales from gold.fact_sales

-- Find how many items are sold

SELECT sum(quantity) AS total_quantity_sold from gold.fact_sales

-- Find the average selling price

SELECT avg(price) AS average_selling_price from gold.fact_sales

-- Find the total number of orders

SELECT count(distinct order_number) AS total_orders from gold.fact_sales

-- Find total number of products

SELECT count(product_key) AS total_products from gold.dim_products
SELECT count(distinct product_key) AS total_products from gold.dim_products

-- Find total number of customers

SELECT count(distinct customer_key) AS total_customers from gold.dim_customers

-- Find total number of customers that has placed an order

SELECT count(distinct customer_key) AS total_customers_with_orders
from gold.fact_sales 

-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, sum(sales_amount) AS measure_value from gold.fact_sales
UNION ALL
SELECT 'Total Quantity', sum(quantity) from gold.fact_sales
UNION ALL
SELECT 'Average Price', avg(price) from gold.fact_sales
UNION ALL
SELECT 'Total Orders',count(distinct order_number) from gold.fact_sales
UNION ALL
SELECT 'Total Products', count(product_key) from gold.dim_products
UNION ALL
SELECT 'Total Customers', count(distinct customer_key) from gold.dim_customers


-- Find total customers by countries

select count(*), country 
from gold.dim_customers 
group by country 

-- Find total customers by gender

select count(*), gender
from gold.dim_customers 
group by gender

-- Find total products by category

select count(*), category
from gold.dim_products
group by category

-- What is the average cost in each category

select category, AVG(cost)
from gold.dim_products
group by category

-- What is total revenue generated for each category

select p.category, sum(s.sales_amount) 
from gold.dim_products p
JOIN gold.fact_sales s
ON p.product_key = s.product_key
group by p.category

-- What is total revenue generated by each customer

select c.customer_key, c.first_name, c.last_name, sum(s.sales_amount) 
from gold.fact_sales s
JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.customer_key, c.first_name, c.last_name

-- What is the distribution of sold items across countries

select c.country, sum(s.quantity) 
from gold.fact_sales s
JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.country

-- Which 5 products generate the highest revenue?


select top 5 p.product_name, sum(s.sales_amount) 
from gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
group by p.product_name
order by 2 desc

-- What are the 5 worst-performing products in terms of sales?

select top 5 p.product_name, sum(s.sales_amount) 
from gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
group by p.product_name
order by 2 asc

-- Find the top 10 customers who have generated the highest revenue


select top 10 c.customer_key, c.first_name, c.last_name, sum(s.sales_amount) AS total_revenue
from gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.customer_key, c.first_name, c.last_name
order by 4 desc

-- Find the 3 customers with the fewest orders placed

select top 3 c.customer_key, c.first_name, c.last_name, count(distinct s.order_number) AS total_orders
from gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.customer_key, c.first_name, c.last_name
order by 4 asc